name: Java + Maven Build App
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Cria um banco de dados Postgres temporário para os testes rodarem
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        # Garante que o workflow só continue depois que o Postgres estiver pronto para receber conexões
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Baixa o codigo fonte para compilar
      - name: 'Baixar o código fonte'
        uses: actions/checkout@v5

      # Configura a versão do JDK
      - name: 'Configura o JDK 21'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Inicia o processo de compilação - com os dados do arquivo de variaveis do
      # ambiente
      - name: 'Compilar o código fonte'
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: 5432
          DB_SERVER: localhost # O container roda localmente na máquina do GitHub
        run: mvn -B clean verify
