name: Java + Maven Build App
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Baixar o código fonte'
        uses: actions/checkout@v4
      - name: 'Configura o JDK 17'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: 'Compilar o código fonte'
        run: mvn -B clean verify
